### ISSUE TITLE
Kodi Nexus 20 module 'xbmc' has no attribute 'translatePath'

### ISSUE THREAD

**Issue by scerazy** [powlo/weather.metoffice#6]
Full log shows:

```
 EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <class 'AttributeError'>
 Error Contents: module 'xbmc' has no attribute 'translatePath'
 Traceback (most recent call last):
   File "/storage/.kodi/addons/weather.metoffice/src/setlocation.py", line 12, in <module>
     from metoffice import utilities, urlcache
   File "/storage/.kodi/addons/weather.metoffice/src/metoffice/utilities.py", line 9, in <module>
     from .constants import WEATHER_WINDOW_ID, ADDON_BROWSER_WINDOW_ID, DIALOG, WINDOW, TEMPERATUREUNITS, ADDON
   File "/storage/.kodi/addons/weather.metoffice/src/metoffice/constants.py", line 21, in <module>
     ADDON_BANNER_PATH = xbmc.translatePath('special://home/addons/%s/resources/banner.png' % ADDON.getAddonInfo('id'))
                         ^^^^^^^^^^^^^^^^^^
 AttributeError: module 'xbmc' has no attribute 'translatePath'
 -->End of Python script error report<--
```
The fix is exactly as here:
https://github.com/melmorabity/plugin.video.francetv/issues/4

Just edit /storage/.kodi/addons/weather.metoffice/src/metoffice/constants.py

```
add, where the existing imports are:

import xbmcvfs

and, lines 22 & 23, change

ADDON_BANNER_PATH = xbmc.translatePath('special://home/addons/%s/resources/banner.png' % ADDON.getAddonInfo('id'))
ADDON_DATA_PATH = xbmc.translatePath('special://profile/addon_data/%s/' % ADDON.getAddonInfo('id'))

to

ADDON_BANNER_PATH = xbmcvfs.translatePath('special://home/addons/%s/resources/banner.png' % ADDON.getAddonInfo('id'))
ADDON_DATA_PATH = xbmcvfs.translatePath('special://profile/addon_data/%s/' % ADDON.getAddonInfo('id'))
```

**Comment by powlo** [comment]
Thanks for the bug report, Nexus hasn't been released as far as I can tell, so that's why there's no weather.metoffice release. But I've got your fix rolled in ready :)
